language: csharp

addons:
  apt:
    packages:
       - msbuild

sudo: false # use the new container-based Travis infrastructure
dist: xenial # Ubuntu 14.04
mono: latest
dotnet: 2.1.500

script:
  - dotnet --info
  - ./build.sh # Release -- dotnet pack not working for net461 on linux