// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("QuotationCompiler")>]
[<assembly: AssemblyProductAttribute("QuotationCompiler")>]
[<assembly: AssemblyDescriptionAttribute("An F# quotation compilation library that uses FSharp.Compiler.Service")>]
[<assembly: AssemblyVersionAttribute("0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "QuotationCompiler"
    let [<Literal>] AssemblyProduct = "QuotationCompiler"
    let [<Literal>] AssemblyDescription = "An F# quotation compilation library that uses FSharp.Compiler.Service"
    let [<Literal>] AssemblyVersion = "0.1"
    let [<Literal>] AssemblyFileVersion = "0.1"
